import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider as Authentication } from "../context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Authentication>
        <body className={inter.className}>{children}</body>
      </Authentication>
    </html>
  );
}
